platform :ios, '14.0'
use_frameworks!

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorBackgroundRunner', :path => '../../node_modules/@capacitor/background-runner'
end

target 'App' do
  project 'App.xcodeproj'
  capacitor_pods
  pod 'CapacitorBackgroundRunner', :path => '../../node_modules/@capacitor/background-runner'
  # Add your Pods here
end
